### ISSUE TITLE
unit-port test fails only in a Release build

### ISSUE THREAD

**Issue by cardboardaardvark** [cardboardaardvark/clypsalot#1]
When running the port unit test in a Release build the test crashes with
> unknown location(0): fatal error: in "link_function": memory access violation at address: 0x562c1c6eac50: invalid permissions

Partial backtrace
```
#0  0x000055555557ac50 in ?? ()
#1  0x00007ffff7fa0e7e in std::function<void ()>::operator()() const (this=0x7fffffffc5a0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:591
#2  Clypsalot::Finally::~Finally (this=<optimized out>) at /home/tyler/Projects/clypsalot/clypsalot/util.cxx:35
#3  0x00007ffff7f981fa in Clypsalot::linkPorts (output=..., input=...) at /home/tyler/Projects/clypsalot/clypsalot/port.cxx:167
#4  0x00005555555582ce in link_function::test_method (this=<optimized out>) at /home/tyler/Projects/clypsalot/test/unit/port.cxx:37
```

**Comment by cardboardaardvark** [comment]
Fixed in commit eaf9d87f1603cb98321b959b39b941977acda6b2
